### ISSUE TITLE
Searching by id for any collection isn't working 

### ISSUE THREAD

**Issue by ManuKothari** [ManuKothari/EduVideo#1]
**/eduvideo/users/<_id>** will not work. But **/eduvideo/users** works and lists all users. Please check.

**Comment by DivyaSarathy** [comment]
Fixed with commit cef5809ac96bfd9147befce8652c9fadd97108c5
Update and delete happens in ui but not in db!!  Just check once.
Or maybe that's coz I don't have net connection in ubuntu?? 
I used Photon for this commit in Windows, but can't use that in ubuntu and something's wrong with my net connection but hopefully it will get fixed by tomorrow.
